### ISSUE TITLE
`make install` na pasta correta para 64 bits

### ISSUE THREAD

**Issue by boppreh** [LabSEC/libcryptosec#15]
Atualmente o target `install` coloca o arquivo `libcryptosec.so` em `/lib/`. Porém para arquiteturas de 64 bits o local correto é `/lib64/`. Isso causa problemas de compilação em outros projetos que dependam da libcryptosec, como a libcryptosec-jni.

**Comment by lucasperin** [comment]
Fixed  in 0b66605
